use_frameworks!

target 'QXFullGestureView_Example' do
  pod 'QXFullGestureView', :path => '../'

  target 'QXFullGestureView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
